#!/bin/bash
#######################################
# Script Name   : 24_file_base_pattern.sh
# Version       : 2.0 #
# Date          : 15/10/2025 #
# Credit        : Vinayak Deokar #
# Purpose       : Write a shell script that renames a large number of files based on a specified pattern or naming convention.#
#######################################


#!/bin/bash

read -p "Enter directory: " DIR
read -p "Enter new prefix: " PREFIX

cd "$DIR" || exit

COUNT=1
for FILE in *; do
  [ -f "$FILE" ] || continue
  EXT="${FILE##*.}"
  mv "$FILE" "${PREFIX}${COUNT}.${EXT}"
  ((COUNT++))
done

echo "Renaming done!"

